name: Deploy self-hosted (Staging & Prod)

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  workflow_dispatch:

jobs:
  staging:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - name: Sanity
        shell: cmd
        run: echo STAGING OK

  prod:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: self-hosted
    steps:
      - name: Sanity
        shell: cmd
        run: echo PROD OK
