name: Deploy (self-hosted → Staging/Prod)

on:
  push:
    branches: [ "main" ]      # staging automático
    tags: [ "v*" ]            # produção por tag vX.Y.Z
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/georgeluch/ecotrack
  DEPLOY_DIR: 'D:\Eco para CI CD\EcoTrack.api (2)\EcoTrack.api'

jobs:
  staging:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - name: Pull & Up Staging (5001)
        shell: cmd
        run: |
          cd /d "%DEPLOY_DIR%"
          docker pull %IMAGE_NAME%:latest
          docker compose -f docker-compose.deploy.staging.yml up -d
          docker compose -f docker-compose.deploy.staging.yml ps

  prod:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: self-hosted
    steps:
      - name: Definir IMAGE_TAG (usa a tag do git, ex.: v1.0.3)
        shell: cmd
        run: |
          echo IMAGE_TAG=%GITHUB_REF_NAME%>> %GITHUB_ENV%

      - name: Pull & Up Production (5000)
        shell: cmd
        run: |
          cd /d "%DEPLOY_DIR%"
          docker pull %IMAGE_NAME%:%IMAGE_TAG%
          docker compose -f docker-compose.deploy.yml up -d
          docker compose -f docker-compose.deploy.yml ps
