name: Deploy (self-hosted → Staging/Prod)

on:
  push:
    branches: [ "main" ]      # staging automático
    tags: [ "v*" ]            # produção por tag
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/georgeluch/ecotrack
  DEPLOY_DIR: 'D:\Eco para CI CD\EcoTrack.api (2)\EcoTrack.api'

jobs:
  staging:
    if: ${{ github.ref_type == 'branch' && github.ref_name == 'main' }}
    runs-on: self-hosted
    steps:
      - name: Pull & Up Staging (5001)
        shell: cmd
        run: |
          cd /d "%DEPLOY_DIR%"
          docker pull %IMAGE_NAME%:latest
          docker compose -f docker-compose.deploy.staging.yml pull
          docker compose -f docker-compose.deploy.staging.yml up -d
          docker compose -f docker-compose.deploy.staging.yml ps

    prod:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: self-hosted
    steps:
      - name: Pull & Up Production (5000)
        shell: cmd
        env:
          IMAGE_TAG: ${{ github.ref_name }}   # <- injeta v1.0.0 no ambiente do step
        run: |
          cd /d "%DEPLOY_DIR%"
          docker compose -f docker-compose.deploy.yml pull
          docker compose -f docker-compose.deploy.yml up -d
          docker compose -f docker-compose.deploy.yml ps

