name: Deploy self-hosted (single job)

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Sanity staging
        if: github.ref == 'refs/heads/main'
        shell: cmd
        run: echo STAGING OK

      - name: Sanity prod
        if: startsWith(github.ref, 'refs/tags/v')
        shell: cmd
        run: echo PROD OK
